version: 2
project_name: jen
builds:
  - dir: cmd/jen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -extldflags "-static"
      - -s
      - -w
      - -X "main.version=v{{ .Version }}"
archives:
  - format: tar.gz
    wrap_in_directory: false
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: silphid
      name: homebrew-tap
    homepage: https://github.com/silphid/jen
    description: >-
      Jen is a CLI tool for scaffolding new microservices based on Go templates,
      onboarding them with your CI/CD and infra, and augmenting them with your
      DevOps scripts for their entire life-time.
    license: MIT
